### ISSUE TITLE
Parent class constants referenced with self do not resolve when defined an array

### ISSUE THREAD

**Issue by pdelre** [goaop/parser-reflection#49] opened 2016-12-07 16:51 UTC
When a parent class constant is referenced with `self` and defined within an array, the value is not resolved.

Stub/FileWithClasses56.php

```php
class ClassWithComplexConstantsAndInheritance extends ClassWithArrayConstants
{
    const K = array(1, NS_CONST56);
    // added self::A
    const L = [self::class, ClassWithArrayConstants::A, parent::B, self::A];
}
``` 

PHPUnit outputs

```
getConstants() for class Go\ParserReflection\Stub\ClassWithComplexConstantsAndInheritance should be equal
Failed asserting that Array &0 (
    'K' => Array &1 (
        0 => 1
        1 => 'test'
    )
    'L' => Array &2 (
        0 => 'Go\ParserReflection\Stub\ClassWithComplexConstantsAndInheritance'
        1 => Array &3 (
            0 => 10
            1 => 11
        )
        2 => Array &4 (
            0 => 42.0
            1 => 43.0
        )
        3 => null
    )
    'A' => Array &5 (
        0 => 10
        1 => 11
    )
    'B' => Array &6 (
        0 => 42.0
        1 => 43.0
    )
) is identical to Array &0 (
    'K' => Array &1 (
        0 => 1
        1 => 'test'
    )
    'L' => Array &2 (
        0 => 'Go\ParserReflection\Stub\ClassWithComplexConstantsAndInheritance'
        1 => Array &3 (
            0 => 10
            1 => 11
        )
        2 => Array &4 (
            0 => 42.0
            1 => 43.0
        )
        3 => Array &5 (
            0 => 10
            1 => 11
        )
    )
    'A' => Array &6 (
        0 => 10
        1 => 11
    )
    'B' => Array &7 (
        0 => 42.0
        1 => 43.0
    )
).
 /Users/pdelre/Projects/github/parser-reflection/tests/ReflectionClassTest.php:299
 /Users/pdelre/Projects/github/parser-reflection/tests/ReflectionClassTest.php:175
```

**Comment by lisachenko** [comment] 2016-12-12 11:03
Hi, could you please test your code against master branch? Could not reproduce your bug...

**Comment by lisachenko** [comment] 2016-12-12 11:56
Reproduced in the master branch: https://travis-ci.org/goaop/parser-reflection/jobs/183215458

**Comment by lisachenko** [comment] 2016-12-12 13:50
Fixed in the master branch now.

**Closed** 2016-12-12 13:49 UTC

**Comment by specdrum-agc** [comment] 2022-11-15 12:14
What about self constants with the name of class itself? Looks like it is not working.

For example:
```
class ClassWithComplexConstantsAndInheritance extends ClassWithArrayConstants
{
    const K = array(1, NS_CONST56);
    const C = array(1,2,3);
    const L = [self::class, ClassWithArrayConstants::A, parent::B, self::A, ClassWithComplexConstantsAndInheritance::C];
}
```
